# Site settings
title: Dental Arch Clinic
description: Blog about dental health tips and best practices
keywords: Dental, Teeth, Health, Dentist, Blogging, Blog
author: Anish Goyal
baseurl: "/b/" # the subpath of your site, e.g. /blog/
url: "dentalarch.in" # the base hostname & protocol for your site
destination: "blogs"
google: "https://plus.google.com/u/0/+DentalArchClinicGurgaon"
linkedin: "https://www.linkedin.com/company/dental-arch-clinic"
facebook: "https://www.facebook.com/dentalarchclinic"
twitter: "https://www.twitter.com/dental_arch"