# Site settings
title: Dental Arch Clinic
description: Blog about dental health tips and best practices
keywords: Dental, Teeth, Health, Dentist, Blogging, Blog
author: Anish Goyal
baseurl: "/b/" # the subpath of your site, e.g. /blog/
url: "dentalarch.in" # the base hostname & protocol for your site
destination: "blogs"
google: "https://plus.google.com/share?url=http://dentalarch.in/b/blogs/"
linkedin: "http://www.linkedin.com/shareArticle?mini=true&url=http://dentalarch.in/b/blogs/&title=Dental+Arch+Clinic+Blog&source=blog"
facebook: "http://www.facebook.com/sharer/sharer.php?u=http://dentalarch.in/b/blogs/&title=Dental+Arch+Clinic+Blog"
twitter: "http://twitter.com/intent/tweet?status=Dental+Arch+Clinic+Blog+http://dentalarch.in/b/blogs/"