# Site settings
title: Careers - Dental Arch
description: Job openings at Dental Arch Clinic
keywords: Dental, Teeth, Health, Dentist, Jobs, Careers
author: Anish Goyal
baseurl: "/c/" # the subpath of your site, e.g. /blog/
url: "dentalarch.in" # the base hostname & protocol for your site
destination: "careers"
google: "https://plus.google.com/u/0/+DentalArchClinicGurgaon"
linkedin: "https://www.linkedin.com/company/dental-arch-clinic"
facebook: "https://www.facebook.com/dentalarchclinic"
twitter: "https://www.twitter.com/dental_arch"
